image: node:14-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

default:
  before_script:
    - yarn install

feeds:lint:
  stage: test
  tags:
    - docker
  script:
    - yarn nx run-many --target=lint --projects=feeds-web-e2e --with-deps

feeds:test:
  stage: test
  tags:
    - docker
  script:
    - yarn nx run-many --target=test --projects=feeds-web-e2e --with-deps

feeds:build:
  stage: build
  tags:
    - docker
  parallel:
    matrix:
      - FEEDS_APP:
          - core
          - discover-ms
          - fetch-ms
          - web
  script:
    - yarn nx run feeds-${FEEDS_APP}:build:production
  artifacts:
    paths:
      - dist/apps/feeds/${FEEDS_APP}
    expire_in: 1 hour

feeds:package:
  stage: package
  needs:
    - feeds:build
  tags:
    - docker
  parallel:
    matrix:
      - FEEDS_APP:
          - core
          - discover-ms
          - fetch-ms
  only:
    - disabled
  image: docker
  before_script:
    - docker login -u "gitlab-ci-token" -p "${CI_JOB_TOKEN}" ${CI_REGISTRY}
    - export DOCKER_IMAGE_NAME=${CI_REGISTRY_IMAGE}/feeds-${FEEDS_APP}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
  script:
    - docker build -f apps/feeds/${FEEDS_APP}/Dockerfile -t ${DOCKER_IMAGE_NAME} .
    - docker push ${DOCKER_IMAGE_NAME}

feeds:deploy:
  stage: deploy
  needs:
    - feeds:package
  tags:
    - deploy
  only:
    - disabled
  variables:
    FEEDS_CORE_DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}/feeds-core/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
    FEEDS_FETCH_MS_DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}/feeds-fetch-ms/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
    FEEDS_DISCOVER_MS_DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}/feeds-discover-ms/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA}
  before_script:
    - docker login -u "gitlab-ci-token" -p "${CI_JOB_TOKEN}" ${CI_REGISTRY}
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
  script:
    - docker-compose -f apps/feeds/docker-compose.deploy.yml pull
